### ISSUE TITLE
'charmap' codec can't decode byte 0x90 in position 316: character maps to <undefined>

### ISSUE THREAD

**Issue by sagarpatel07** [mak4lab/person-extractor#1]
when trying to install module using "pip install person-extractor" it throws below error.
   Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XXX\AppData\Local\Temp\pip-install-8iir35tm\person-extractor\setup.py", line 7, in <module>
        long_description = f.read()
      File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 316: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by DanielJDufour** [comment]
Hi, @sagarpatel07 .  Thanks for posting this issue.  We'll try to fix it.  Do you happen to know if you were using Python 2 or 3?

**Comment by sagarpatel07** [comment]
@DanielJDufour using Python3
